package com.zhiyou.colleageapp.constants;

/**
 * Author by LongWei Hu on 2016/5/22.
 */
public interface FragmentTag {
    /**
     * 会话列表界面 to 通讯录界面
     */
    String CONTACT_LIST = "CONTACT_LIST";
    String CONTACT_LIST_2_NEW_FRIEND = "CONTACT_LIST_2_NEW_FRIEND";
    String CONTACT_LIST_2_NEARBY_PERSON = "CONTACT_LIST_2_NEARBY_PERSON";
    String FRAGMENT_CONVERSATION_2_DYNAMIC = "FRAGMENT_CONVERSATION_2_DYNAMIC";
    String FRAGMENT_FRIEND_2_CREATE_GROUP = "FRAGMENT_FRIEND_2_CREATE_GROUP";
    String TREEHOLE_2_PUB = "TREEHOLE_2_PUB";
    String CONTACT_LIST_2_ADD_CONTACT = "CONTACT_LIST_2_ADD_CONTACT";
    String SOCIETY_2_WEBVIEW = "SOCIETY_2_WEBVIEW";
    String FRAGMENT_CREATE_GROUP_2_PICK_CONTACT = "FRAGMENT_CREATE_GROUP_2_PICK_CONTACT";
    String GROUP_CHAT = "GROUP_CHAT";
    String FRAGMENT_GROUP_DETAIL_2_GROUP_PICK_CONTACTS = "FRAGMENT_GROUP_DETAIL_2_GROUP_PICK_CONTACTS";
    String GROUP_DETAIL_2_GROUP_BLACK_LIST = "GROUP_DETAIL_2_GROUP_BLACK_LIST";
    String GROUP_DETAIL_2_EDIT_GROUP_NAME = "GROUP_DETAIL_2_EDIT_GROUP_NAME";
    String CHAT_FRAGMENT_2_GROUP_DETAIL = "CHAT_FRAGMENT_2_GROUP_DETAIL";
    String GROUP_2_CHAT = "GROUP_2_CHAT";
    String CREATE_GROUP_2_CHAT = "CREATE_GROUP_2_CHAT";
    String CONVERSATION_2_CHAT = "CONVERSATION_2_CHAT";
    String CONTACT_LIST_2_CHAT = "CONTACT_LIST_2_CHAT";
    String FRIEND_INFO = "FRIEND_INFO";
    /**
     * 生活界面 to 生活二级界面
     */
    String LIFE_2_TAOYU = "LIFE_2_TAOYU";
    String LIFE_2_TALK = "LIFE_2_TALK";
    String LIFE_2_PLAY = "LIFE_2_PLAY";
    String LIFE_2_GROUPACTLIST = "LIFE_2_GROUPACTLIST";
    String LIFE_2_GROUPACT = "LIFE_2_GROUPACT";
    String LIFE_2_SCHOOLACTLIST = "LIFE_2_SCHOOLACTLIST";
    String LIFE_2_TREEHOEL = "LIFE_2_TREEHOEL";
    String LIFE_2_OFFER = "LIFE_2_OFFER";
    String TREEHOLE_2_DETAIL = "TREEHOLE_2_DETAIL";
    String PLAY_2_SCHOOLACT = "PLAY_2_SCHOOLACT";
    String PLAY_2_TAOYUDETAIL = "PLAY_2_TAOYUDETAIL";
    String TAOYU_2_PUB = "TAOYU_2_PUB";
    String PLAY_2_OFFERDETAIL = "PLAY_2_OFFERDETAIL";

    /**
     * 个人中心 to 二级界面
     */
    String MINE_2_LOVE = "MINE_2_LOVE";
    String MINE_2_INFO = "MINE_2_INFO";
    String MINE_2_SETTING = "MINE_2_SETTING";
    String LIST_2_VIDEO = "LIST_2_VIDEO";
    String LOVE_2_CARD = "LOVE_2_CARD";
    String RECORDVIDEO_2_EDITOR = "RECORDVIDEO_2_EDITOR";
    String CONTACT_LIST_2_FRIEND_INFO ="CONTACT_LIST_2_FRIEND_INFO";
    String BASE_CHAT_2_FRIEND_INFO = "BASE_CHAT_2_FRIEND_INFO";

    String CHAT_SINGLE = "CHAT_SINGLE";
    String DYNAMIC = "DYNAMIC";
    String JOIN_GROUP = "JOIN_GROUP";
    String EDIT_PERSONAL_INFO = "EDIT_PERSONAL_INFO";

    String PERSONAL_INFO = "PERSONAL_INFO";
}
