package com.zhiyou.colleageapp.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.zhiyou.colleageapp.eenum.InviteMsgStatus;

/**
 * Entity mapped to table "INVITE_MESSAGE".
 */
public class InviteMessage {

    private String mGroupId;
    private String mMsgId;
    private String mGroupName;
    private String mReason;
    private InviteMsgStatus mMsgStatus;
    private Boolean mIsInviteFromMe;
    private Integer mMsgUnreadCount;
    private Long mTimeStamp;
    /**
     * 邀请人的id
     */
    private String mInviteeId;
    /**
     * 邀请人的名字
     */
    private String mFromName;

    public InviteMessage() {
    }

    public InviteMessage(String MsgId) {
        this.mMsgId = MsgId;
    }

    public String getFrom() {
        return mFromName;
    }

    public void setFrom(String from) {
        mFromName = from;
    }

    public String getMsgId() {
        return mMsgId;
    }

    public void setMsgId(String MsgId) {
        this.mMsgId = MsgId;
    }

    public String getGroupId() {
        return mGroupId;
    }

    public void setGroupId(String GroupId) {
        this.mGroupId = GroupId;
    }

    public String getGroupName() {
        return mGroupName;
    }

    public void setGroupName(String GroupName) {
        this.mGroupName = GroupName;
    }

    public String getReason() {
        return mReason;
    }

    public void setReason(String Reason) {
        this.mReason = Reason;
    }

    public InviteMsgStatus getMsgStatus() {
        return mMsgStatus;
    }

    public void setMsgStatus(InviteMsgStatus MsgStatus) {
        this.mMsgStatus = MsgStatus;
    }

    public Boolean getIsInviteFromMe() {
        return mIsInviteFromMe;
    }

    public void setIsInviteFromMe(Boolean IsInviteFromMe) {
        this.mIsInviteFromMe = IsInviteFromMe;
    }

    public Integer getMsgUnreadCount() {
        return mMsgUnreadCount;
    }

    public void setMsgUnreadCount(Integer MsgUnreadCount) {
        this.mMsgUnreadCount = MsgUnreadCount;
    }

    public Long getTimeStamp() {
        return mTimeStamp;
    }

    public void setTimeStamp(Long TimeStamp) {
        this.mTimeStamp = TimeStamp;
    }

    public String getInviteeId() {
        return mInviteeId;
    }

    public void setInviteeId(String GroupInviter) {
        this.mInviteeId = GroupInviter;
    }

    @Override
    public String toString() {
        return "InviteMessage{" +
                "mMsgId='" + mMsgId + '\'' +
                ", mGroupId='" + mGroupId + '\'' +
                ", mGroupName='" + mGroupName + '\'' +
                ", mReason='" + mReason + '\'' +
                ", mMsgStatus=" + mMsgStatus +
                ", mIsInviteFromMe=" + mIsInviteFromMe +
                ", mMsgUnreadCount=" + mMsgUnreadCount +
                ", mTimeStamp=" + mTimeStamp +
                ", mInviteeId='" + mInviteeId + '\'' +
                ", mFromName='" + mFromName + '\'' +
                '}';
    }
}
