package com.zhiyou.colleageapp.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.annotation.SuppressLint;

import com.hyphenate.chat.EMMessage;
import com.hyphenate.chat.adapter.message.EMAMessage;

/**
 * Entity mapped to table "MESSAGE".
 */
@SuppressLint("ParcelCreator")
public class Message extends EMMessage {

    private String ConversationId;
    private String SpeakerId;
    private Integer SessionType;
    private String Content;
    private Integer DeviceType;
    private Double MsgVersion;

    public Message(EMAMessage emaMessage) {
        super(emaMessage);
    }



    public void setType(String type) {

    }

    public String getConversationId() {
        return ConversationId;
    }

    public void setConversationId(String ConversationId) {
        this.ConversationId = ConversationId;
    }

    public String getSpeakerId() {
        return SpeakerId;
    }

    public void setSpeakerId(String SpeakerId) {
        this.SpeakerId = SpeakerId;
    }

    public Integer getSessionType() {
        return SessionType;
    }

    public void setSessionType(Integer SessionType) {
        this.SessionType = SessionType;
    }


    public String getContent() {
        return getBody().toString();
    }

    public void setContent(String Content) {
        this.Content = Content;
    }

    public Integer getStatus() {
        return status().ordinal();
    }
    public Integer getDeviceType() {
        return DeviceType;
    }

    public void setDeviceType(Integer DeviceType) {
        this.DeviceType = DeviceType;
    }

    public Double getMsgVersion() {
        return MsgVersion;
    }

    public void setMsgVersion(Double MsgVersion) {
        this.MsgVersion = MsgVersion;
    }

}
