package com.zhiyou.colleageapp.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PREF".
 * 这个类是User相关的类，用来处理User的组相关的信息
 */
public class Pref {

    private String DisableGroupId;
    private String UserId;
    private String DisableGroupName;

    public Pref() {
    }

    public Pref(String DisableGroupId) {
        this.DisableGroupId = DisableGroupId;
    }

    public Pref(String DisableGroupId, String UserId, String DisableGroupName) {
        this.DisableGroupId = DisableGroupId;
        this.UserId = UserId;
        this.DisableGroupName = DisableGroupName;
    }

    public String getDisableGroupId() {
        return DisableGroupId;
    }

    public void setDisableGroupId(String DisableGroupId) {
        this.DisableGroupId = DisableGroupId;
    }

    public String getUserId() {
        return UserId;
    }

    public void setUserId(String UserId) {
        this.UserId = UserId;
    }

    public String getDisableGroupName() {
        return DisableGroupName;
    }

    public void setDisableGroupName(String DisableGroupName) {
        this.DisableGroupName = DisableGroupName;
    }

}
