package com.zhiyou.colleageapp.domain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.text.TextUtils;

import com.google.gson.annotations.SerializedName;
import com.zhiyou.colleageapp.constants.HttpKey;
import com.zhiyou.colleageapp.eenum.Gender;

/**
 * Entity mapped to table "USER".
 */
public class User extends Person{


    @SerializedName(HttpKey.SEX)
    private int mGender;
//    private Gender mGender;
    @SerializedName(HttpKey.NICK_NAME)
    private String mNick;
    /**
     * 标识该用户的来源
     */
    @SerializedName(HttpKey.BELONG)
    private String mBelong;

    public User(String userName) {
        mUserName = userName;
    }

    public User() {
    }

    /**
     * 昵称首字母
     */

    protected String mInitialLetter;

    public String getNick() {
        return mNick;
    }

    public void setNick(String nick) {
        mNick = nick;
    }

    public String getBelong() {
        return mBelong;
    }

    public void setBelong(String belong) {
        mBelong = belong;
    }



    public Gender getGender() {
        return Gender.valueFromInt(mGender) ;
    }

    public void setGender(Gender gender) {
        this.mGender = gender.getValue();
    }

    public String getInitialLetter() {

        if (!TextUtils.isEmpty(mInitialLetter)) {
            return mInitialLetter;
        } else if (!TextUtils.isEmpty(getNick())) {
            return getNick();
        } else if (!TextUtils.isEmpty(getUsername())) {
            return getUsername();
        } else {
            return "";
        }

    }

    public void setInitialLetter(String initialLetter) {
        this.mInitialLetter = initialLetter;
    }

    @Override
    public String toString() {
        return "User{" +
                "Avatar='" + mAvatar + '\'' +
                ", mGender=" + mGender +
                ", mUserName='" + mUserName + '\'' +
                ", mNick='" + mNick + '\'' +
                ", mBelong='" + mBelong + '\'' +
                ", mInitialLetter='" + mInitialLetter + '\'' +
                '}';
    }
}
